version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=thenewboston_node
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  node:
    build: .
    image: thenewboston-node:current
    environment:
      - IN_DOCKER=true
      - THENEWBOSTON_NODE_DATABASES={"default":{"HOST":"db"}}
    env_file:
      - .env
    command: ./run.sh
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgresql-data:
    driver: local
