version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local
