version: '3.9'

services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=thenewboston_node
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  reverse-proxy:
    image: docker.pkg.github.com/thenewboston-developers/thenewboston-node/thenewboston-node-reverse-proxy:latest
    ports:
      - 8555:8555
    volumes:
      - type: volume
        source: nginx-conf.d
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
        read_only: true
      - type: volume
        source: blockchain
        target: /var/lib/blockchain
        volume:
          nocopy: true
        read_only: true
    depends_on:
      # Depends on node to get /etc/nginx/conf.d/node.conf
      - node

  node:
    image: docker.pkg.github.com/thenewboston-developers/thenewboston-node/thenewboston-node:latest
    environment:
      - THENEWBOSTON_NODE_DATABASES={"default":{"HOST":"db"}}
    env_file: .env
    command: ./run.sh
    depends_on:
      - db
    volumes:
      - nginx-conf.d:/etc/nginx/conf.d
      - blockchain:/var/lib/blockchain

volumes:
  postgresql-data:
    driver: local
  nginx-conf.d:
    driver: local
  blockchain:
    driver: local
