[tool.poetry]
name = "thenewboston-node"
version = "0.1.0"
description = ""
authors = ["Bucky Roberts <buckyroberts@gmail.com>"]
license = "MIT"
packages = [
    { include = "thenewboston_node" },
]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"
Django = "*"
psycopg2 = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
