[tool.poetry]
name = "thenewboston-node"
version = "0.1.0"
description = ""
authors = ["Bucky Roberts <buckyroberts@gmail.com>"]
license = "MIT"
packages = [
    { include = "thenewboston_node" },
]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"
Django = ">=3.1.7"
psycopg2 = "*"

[tool.poetry.dev-dependencies]
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-xdist = "*"
requests-mock = "*"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "thenewboston_node.project.settings"
python_files = "test_*.py"
testpaths = ["thenewboston_node"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
