name: Documentation

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    name: Documentation

    runs-on: ubuntu-latest
    container: python:3.9.2

    services:
      # TODO(dmu) LOW: Make database not required to generate documentation
      db:
        image: postgres:13.2-alpine
        env:
          POSTGRES_DB: thenewboston_node
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Install
        run: make install

      - name: Generate
        run: make docs-html
