name: Documentation

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    name: Documentation

    runs-on: ubuntu-latest
    container: python:3.9.2

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Install
        run: make install

      - name: Generate
        run: make docs-html
        env:
          THENEWBOSTON_NODE_SECRET_KEY: dummy
