name: Package

on:
  push:
    branches:
      - master
    # TODO(dmu) HIGH: Enable the disable package pulbication
    branches-ignore:
      - '**'

jobs:
  # TODO(dmu) CRITICAL: Do not publish if unittests do not pass
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push to GitHub Packages
        # TODO(dmu) HIGH: Upgrade to `docker/build-push-action@v2`
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: thenewboston-developers/thenewboston-node/thenewboston-node
          tag_with_ref: true
